[build-system]
requires = ["setuptools>=61.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "firefly-csv-converter"
dynamic = ["version"]
description = "Tools to convert and clean bank CSVs into Firefly III import format."
authors = [{ name = "Renato Costa", email = "renato@ccosta.dev"}]
readme = "README.md"
license-files = ["COPYING"]
requires-python = ">=3.11"
dependencies = ["pandas (>=2.3.3,<3.0.0)", "openpyxl (>=3.1.5,<4.0.0)"]

[dependency-groups]
test = ["pytest", "pytest-cov"]

[project.scripts]
convert-bb-cp = "scripts.convert_bb_cp:main"

[tool.setuptools.packages.find]
include = ["scripts*"]
exclude = ["tests*", "samples*", "output*"]

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "no-local-version"

[tool.poetry]
version = "1.0"  # base version