[build-system]
requires = ["setuptools>=61.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "firefly-csv-converter"
dynamic = ["version"]
description = "Tools to convert and clean bank CSVs into Firefly III import format."
authors = [{ name = "Renato Costa" }]
readme = "README.md"
license-files = ["COPYING"]
dependencies = [
    "pandas",
]

[project.scripts]
convert-bb-cp = "scripts.convert_bb_cp:main"

[tool.setuptools.packages.find]
include = ["scripts*"]
exclude = ["tests*", "samples*", "output*"]

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "no-local-version"